<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etiqueta [
<!ELEMENT etiqueta (nombre,calle,ciudad,pais,codigo)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT codigo (#PCDATA)>
]>

<etiqueta>
    <nombre>Roberto Garcia</nombre>
    <calle>c/ Mayor,27</calle>
    <ciudad>Coslada</ciudad>
    <pais>Espa√±a</pais>
    <codigo>39343</codigo>
</etiqueta>