<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE oferta [
    <!ELEMENT oferta (vehiculo*)>
    <!ELEMENT vehiculo (marca,modelo,motor,matricula,kilometros,precio_inicial,precio_oferta,extras,fotos)>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT motor (#PCDATA)>
    <!ELEMENT kilometros (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT precio_inicial (#PCDATA)>
    <!ELEMENT precio_oferta (#PCDATA)>
    <!ELEMENT extras (extra*)>
        <!ELEMENT extra (#PCDATA)>
    <!ELEMENT fotos (foto*)>
        <!ELEMENT foto (#PCDATA)>
    <!ATTLIST vehiculo color CDATA #REQUIRED>
    <!ATTLIST motor tipo NMTOKEN #IMPLIED>
    <!ATTLIST foto tipoFoto (frontal|trasera|lateral|interior) "frontal">
    <!ATTLIST vehiculo color CDATA #REQUIRED>
    <!ATTLIST matricula anyo CDATA #REQUIRED>
    <!ENTITY  pmetal  "pintura metalizada">
]>
<oferta>
    <vehiculo color="rojo">
        <marca>ford</marca>
        <modelo>focus</modelo>
        <motor tipo="diesel">duratore 1.4</motor>
        <matricula anyo="2014">1234AAAA</matricula>
        <kilometros>12500</kilometros>
        <precio_inicial>12000</precio_inicial>
        <precio_oferta>10000</precio_oferta>
        <extras>
        <extra>llantas</extra>
        <extra>&pmetal;</extra>
        </extras>
        <fotos>
        <foto tipoFoto="frontal">11325.jpg</foto>
        <foto tipoFoto="interior">11326.jpg</foto>
        <foto>11345.jpg</foto>
        </fotos>
        </vehiculo>
        <vehiculo color="azul oscuro">
        <marca>ford</marca>
        <modelo>focus</modelo>
        <motor tipo="gasolina">duratore 2.0</motor>
        <matricula anyo="2015">12345AAA</matricula>
        <kilometros>125000</kilometros>
        <precio_inicial>10000</precio_inicial>
        <precio_oferta>9000</precio_oferta>
        <extras>
        <extra>&pmetal;</extra>
        <extra>spoiler trasero</extra>
        <extra>climatizador</extra>
        </extras>
        <fotos>
        <foto tipoFoto="frontal">11345.jpg</foto>
        </fotos>
        </vehiculo>
</oferta>